''' Totally trained on these 80 classes '''
objects = {
    "wine glass",
    "bottle",
    "baseball glove",
    "baseball bat",
    "banana",
    "backpack",
    "apple",
    "train",
    "vase",
    "umbrella",
    "tv",
    "truck",
    "traffic light",
    "toothbrush",
    "toilet",
    "tie",
    "tennis racket",
    "teddy bear",
    "surfboard",
    "suitcase",
    "stop sign",
    "spoon",
    "skis",
    "skateboard",
    "sink",
    "remote",
    "sheep",
    "scissors",
    "refrigerator",
    "potted plant",
    "pizza",
    "person",
    "parking meter",
    "oven",
    "mouse",
    "motorcycle",
    "microwave",
    "laptop",
    "knife",
    "kite",
    "keyboard",
    "hot dog",
    "horse",
    "handbag",
    "hair drier",
    "frisbee",
    "fork",
    "fire hydrant",
    "donut",
    "elephant",
    "dog",
    "dining table",
    "cup",
    "cow",
    "couch",
    "clock",
    "chair",
    "cell phone",
    "cat",
    "carrot",
    "car",
    "cake",
    "bus",
    "broccoli",
    "bowl",
    "book",
    "boat",
    "bird",
    "bicycle",
    "bench",
    "bed",
    "airplane",
    "bear",
    "giraffe",
    "orange",
    "sandwich",
    "snowboard",
    "toaster",
    "zebra",
    "sports ball"
}
